version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: gaegxh
      POSTGRES_PASSWORD: 173617
      POSTGRES_DB: districtnet
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
