name: CI - Build and Test

on:
    push:
        branches: [develop]
    pull_request:
        branches: [develop]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        environment: SPRING_DATASOURCE_USERNAME

        env:
            SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
            POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  distribution: 'temurin'
                  java-version: '17'

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Start services with Docker Compose
              run: docker compose up -d

            - name: Grant execute permission to Gradle wrapper
              run: chmod +x ./gradlew

            - name: Build project
              run: SPRING_PROFILES_ACTIVE=ci ./gradlew build

            - name: Run tests
              run: ./gradlew test

            - name: Stop Docker Compose
              run: docker compose down
