name: CI - Build and Test

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_USERNAME: gaegxh
      SPRING_DATASOURCE_PASSWORD: 173617
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/districtnet
      POSTGRES_USER: gaegxh
      POSTGRES_PASSWORD: 173617
      POSTGRES_DB: districtnet

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo apt-get install -y docker-compose

      - name: Create .env file
        run: |
          echo "SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}" > .env
          echo "SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}" >> .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          echo "POSTGRES_DB=${POSTGRES_DB}" >> .env
          echo "SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}" >> .env

      - name: Start services with Docker Compose
        run: |
          sudo docker-compose up -d
        # если docker-compose.yml не в корне:
        # run: docker-compose -f path/to/docker-compose.yml up -d

      - name: Wait for Postgres to be ready
        run: |
          until docker exec $(docker ps -qf "name=districtnet") pg_isready -U ${POSTGRES_USER}; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build project
        run: SPRING_PROFILES_ACTIVE=ci ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Stop Docker Compose
        run: |
          sudo docker-compose down
